### ISSUE TITLE
Net Core 2.2 compatibility

### ISSUE THREAD

**Issue by dedo1911** [brantburnett/Snappier#99]
I've a library that's using Snappier 1.1.6, and once imported in a Net Core 2.2 app, I get the following error message, blocking my build:

```
System.Runtime.CompilerServices.Unsafe doesn't support netcoreapp2.2. Consider updating your TargetFramework to netcoreapp3.1 or later.
```

Which is in contrast to the readme of Snappier:
> Compatible with .NET 4.6.1 and later and .NET Core 2.0 and later

Is there a specific Snappier version that can run on Core 2.2?
Thanks

**Comment by brantburnett** [comment]
I must have forgotten to update the documentation. .NET Core 2.2 has been out of support since 2019, so Snappier no longer supports it either. It also wouldn't perform well on such an old version due to the lack of support for CPU intrinsics in that runtime.  You could use the old 1.0.0 version, though, it was compatible with 2.2 via a specific target for 2.0.
